version: '3.2'

services:
  php-fpm:
    container_name: bag-api
    image: docker.tgnb.cc/bag/php-service:1.0
    ports:
      - "9000:9000"
    volumes:
      - ./api.admin/:/data/www/api.admin/:rw
      - ./api.www/:/data/www/api.www/:rw
      - ./config/:/data/www/config/:rw
      - ./jobs/:/data/www/jobs/:rw
      - ./repo/:/data/www/repo/:rw
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  nginx:
    container_name: bag-nginx
    image: docker.tgnb.cc/bag/nginx-service:1.0
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ./api.admin/:/data/www/api.admin/:rw
      - ./api.www/:/data/www/api.www/:rw
      - ./config/:/data/www/config/:rw
      - ./jobs/:/data/www/jobs/:rw
      - ./repo/:/data/www/repo/:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl/:/etc/nginx/ssl
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

