
#更新银行表数据
ALTER TABLE `bank` 
ADD COLUMN `code_num` char(3) NULL DEFAULT 000 COMMENT '银行代码' AFTER `code`;

TRUNCATE TABLE bank;

INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (1, 'KBANK', '004', 0, 'enabled', 'KASIKORNBANK PCL', 'KBANK', NULL, 'https://update.a1jul.com/kgb/bank/KBANK.png', NULL, 0, '2022-02-18 16:49:22', '2022-02-18 16:49:22', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (2, 'BBL', '002', 0, 'enabled', 'BANGKOK BANK PUBLIC COMPANY LTD.', 'BBL', NULL, 'https://update.a1jul.com/kgb/bank/BBL.png', NULL, 0, '2022-02-18 16:50:08', '2022-02-18 16:50:08', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (3, 'BAAC', '034', 0, 'enabled', 'BANK FOR AGRICULTURE AND AGRICULTURAL CO-OPERATIVES', 'BAAC', NULL, 'https://update.a1jul.com/kgb/bank/BAAC.png', NULL, 0, '2022-02-18 17:04:44', '2022-02-18 17:04:44', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (4, 'BOA', '0', 0, 'enabled', 'BANK OF AMERICA NT&SA', 'BOA', NULL, 'https://update.a1jul.com/kgb/bank/BOA.png', NULL, 0, '2022-01-12 16:01:59', '2022-01-12 16:01:59', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (5, 'BAY', '025', 0, 'enabled', 'BANK OF AYUDHAYA PUBLIC COMPANY LTD.', 'BAY', NULL, 'https://update.a1jul.com/kgb/bank/BAY.png', NULL, 0, '2022-02-18 16:58:54', '2022-02-18 16:58:54', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (6, 'BOC', '052', 0, 'enabled', 'Bank of China (Thai) PCL', 'BOC', NULL, 'https://update.a1jul.com/kgb/bank/BOC.png', NULL, 0, '2022-02-18 17:08:38', '2022-02-18 17:08:38', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (7, 'BNPP', '0', 0, 'enabled', 'BNP PARIBAS BANGKOK BRANCH', 'BNPP', NULL, 'https://update.a1jul.com/kgb/bank/BNPP.png', NULL, 0, '2022-01-12 16:01:59', '2022-01-12 16:01:59', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (8, 'CIMB', '022', 0, 'enabled', 'CIMB THAI BANK PUBLIC COMPANY LTD.', 'CIMB', NULL, 'https://update.a1jul.com/kgb/bank/CIMB.png', NULL, 0, '2022-02-18 17:01:15', '2022-02-18 17:01:15', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (9, 'CITI', '017', 0, 'enabled', 'CITI BANK N.A.', 'CITI', NULL, 'https://update.a1jul.com/kgb/bank/CITI.png', NULL, 0, '2022-02-18 17:21:15', '2022-02-18 17:21:15', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (10, 'DB', '032', 0, 'enabled', 'Deutsche Bank AG', 'DB', NULL, 'https://update.a1jul.com/kgb/bank/DB.png', NULL, 0, '2022-02-18 17:02:23', '2022-02-18 17:02:23', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (11, 'GHB', '033', 0, 'enabled', 'GOVERNMENT HOUSING BANK', 'GHB', NULL, 'https://update.a1jul.com/kgb/bank/GHB.png', NULL, 0, '2022-02-18 17:07:16', '2022-02-18 17:07:16', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (12, 'ICBC', '070', 0, 'enabled', 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (THAI) PCL', 'ICBC', NULL, 'https://update.a1jul.com/kgb/bank/ICBC.png', NULL, 0, '2022-02-18 17:07:48', '2022-02-18 17:07:48', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (13, 'TIBT', '066', 0, 'enabled', 'ISLAMIC BANK OF THAILAND', 'TIBT', NULL, 'https://update.a1jul.com/kgb/bank/TIBT.png', NULL, 0, '2022-02-18 17:07:33', '2022-02-18 17:07:33', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (14, 'CHAS', '0', 0, 'enabled', 'JPMorgan Chase Bank, Bangkok Branch', 'CHAS', NULL, 'https://update.a1jul.com/kgb/bank/CHAS.png', NULL, 0, '2022-01-12 16:01:59', '2022-01-12 16:01:59', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (15, 'KKB', '069', 0, 'enabled', 'KIATNAKIN BANK PCL', 'KKB', NULL, 'https://update.a1jul.com/kgb/bank/KKB.png', NULL, 0, '2022-02-18 16:59:45', '2022-02-18 16:59:45', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (16, 'KTB', '006', 0, 'enabled', 'KRUNG THAI BANK PUBLIC COMPANY LTD.', 'KTB', NULL, 'https://update.a1jul.com/kgb/bank/KTB.png', NULL, 0, '2022-02-18 16:59:13', '2022-02-18 16:59:13', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (17, 'LHBA', '073', 0, 'enabled', 'Land and Houses Bank', 'LHBA', NULL, 'https://update.a1jul.com/kgb/bank/LHBA.png', NULL, 0, '2022-02-18 17:06:19', '2022-02-18 17:06:19', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (18, 'MEGA', '0', 0, 'enabled', 'MEGA  INTERNATIONAL COMMERCIAL BANK', 'MEGA', NULL, 'https://update.a1jul.com/kgb/bank/MEGA.png', NULL, 0, '2022-01-12 16:01:59', '2022-01-12 16:01:59', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (19, 'MHCB', '039', 0, 'enabled', 'MIZUHO CORPORATE BANK', 'MHCB', NULL, 'https://update.a1jul.com/kgb/bank/MHCB.png', NULL, 0, '2022-02-18 17:05:00', '2022-02-18 17:05:00', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (20, 'SCBT', '020', 0, 'enabled', 'STANDARD CHARTERED BANK THAI PCL.', 'SCBT', NULL, 'https://update.a1jul.com/kgb/bank/SCBT.png', NULL, 0, '2022-02-18 17:06:37', '2022-02-18 17:06:37', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (21, 'SMTB', '080', 0, 'enabled', 'Sumitomo Mitsui Trust Bank (Thai) PCL.', 'SMTB', NULL, 'https://update.a1jul.com/kgb/bank/SMTB.png', NULL, 0, '2022-02-18 17:23:28', '2022-02-18 17:23:28', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (22, 'TTB', '011', 0, 'enabled', 'TMBThanachart', 'TTB', NULL, 'https://update.a1jul.com/kgb/bank/TTB.png', NULL, 0, '2022-02-18 17:03:03', '2022-02-18 17:03:03', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (23, 'GSB', '030', 0, 'enabled', 'THE GOVERNMENT SAVING BANK', 'GSB', NULL, 'https://update.a1jul.com/kgb/bank/GSB.png', NULL, 0, '2022-02-18 17:06:59', '2022-02-18 17:06:59', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (24, 'HSBC', '031', 0, 'enabled', 'THE HONGKONG & SHANGHAI CORPORATION LTD.', 'HSBC', NULL, 'https://update.a1jul.com/kgb/bank/HSBC.png', NULL, 0, '2022-02-18 17:08:20', '2022-02-18 17:08:20', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (25, 'SCB', '014', 0, 'enabled', 'THE SIAM COMMERCIAL BANK PUBLIC COMPANY', 'SCB', NULL, 'https://update.a1jul.com/kgb/bank/SCB.png', NULL, 0, '2022-02-18 17:03:57', '2022-02-18 17:03:57', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (26, 'SMBC', '018', 0, 'enabled', 'THE SUMITOMO MITSU BANKING CORPORATION', 'SMBC', NULL, 'https://update.a1jul.com/kgb/bank/SMBC.png', NULL, 0, '2022-02-18 17:01:55', '2022-02-18 17:01:55', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (27, 'TCRB', '071', 0, 'enabled', 'THE THAI CREDIT RETAIL BANK', 'TCRB', NULL, 'https://update.a1jul.com/kgb/bank/TCRB.png', NULL, 0, '2022-02-18 17:03:44', '2022-02-18 17:03:44', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (28, 'TISCO', '067', 0, 'enabled', 'TISCO Bank PCL', 'TISCO', NULL, 'https://update.a1jul.com/kgb/bank/TISCO.png', NULL, 0, '2022-02-18 17:03:25', '2022-02-18 17:03:25', NULL, 1);
INSERT INTO `bank` (`id`, `code`, `code_num`, `sort`, `status`, `name`, `shortname`, `url`, `h5_logo`, `logo`, `created_uid`, `created`, `updated`, `updated_uid`, `type`) VALUES (29, 'UOB', '024', 0, 'enabled', 'UNITED OVERSEAS BANK (THAI) PUBLIC COMPANY LTD.', 'UOB', NULL, 'https://update.a1jul.com/kgb/bank/UOB.png', NULL, 0, '2022-02-18 17:05:57', '2022-02-18 17:05:57', NULL, 1);

#更新代付关联银行

UPDATE `transfer_config` SET `bank_list` = '{\"KBANK\":\"KBANK\",\"BBL\":\"BBL\",\"BAAC\":\"BAAC\",\"BAY\":\"BAY\",\"BOC\":\"BOC\",\"CIMB\":\"CIMB\",\"CITI\":\"CITI\",\"DB\":\"DB\",\"GHB\":\"GHB\",\"ICBC\":\"ICBC\",\"TIBT\":\"TIBT\",\"KKB\":\"KKB\",\"KTB\":\"KTB\",\"LHBA\":\"LHBA\",\"MHCB\":\"MHCB\",\"SCBT\":\"SCBT\",\"TTB\":\"TTB\",\"GSB\":\"GSB\",\"HSBC\":\"HSBC\",\"SCB\":\"SCB\",\"SMBC\":\"SMBC\",\"TCRB\":\"TCRB\",\"TISCO\":\"TISCO\",\"UOB\":\"UOB\"}' WHERE `code` = 'BCQR';

UPDATE `transfer_config` SET `bank_list` = '{\"KBANK\":\"KBANK\",\"BBL\":\"BBL\",\"BAAC\":\"BAAC\",\"BAY\":\"BAY\",\"BOC\":\"BOC\",\"CIMB\":\"CIMB\",\"CITI\":\"CITI\",\"DB\":\"DB\",\"GHB\":\"GHB\",\"ICBC\":\"ICBC\",\"TIBT\":\"TIBT\",\"KKB\":\"KKB\",\"KTB\":\"KTB\",\"LHBA\":\"LHBA\",\"MHCB\":\"MHCB\",\"SCBT\":\"SCBT\",\"TTB\":\"TTB\",\"GSB\":\"GSB\",\"HSBC\":\"HSBC\",\"SCB\":\"SCB\",\"SMBC\":\"SMBC\",\"TCRB\":\"TCRB\",\"TISCO\":\"TISCO\",\"UOB\":\"UOB\"}' WHERE `code` = 'TUPAY';

UPDATE `transfer_config` SET `bank_list` = '{\"KBANK\":\"KBANK\",\"BBL\":\"BBL\",\"BAAC\":\"BAAC\",\"BAY\":\"BAY\",\"BOC\":\"BOC\",\"CIMB\":\"CIMB\",\"CITI\":\"CITI\",\"GHB\":\"GHB\",\"ICBC\":\"ICBC\",\"TIBT\":\"TIBT\",\"KKB\":\"KKB\",\"KTB\":\"KTB\",\"LHBA\":\"LHBA\",\"SCBT\":\"SCBT\",\"SMTB\":\"SMTB\",\"TTB\":\"TTB\",\"GSB\":\"GSB\",\"SCB\":\"SCB\",\"TCRB\":\"TCRB\",\"TISCO\":\"TISCO\",\"UOB\":\"UOB\"}' WHERE `code` = 'PROMPTPAY';

#YFB代付限额
update transfer_config set min_money = 10100 , max_money = 4999900 where `name` = "YFBPAY";