INSERT INTO `game_menu`(`id`, `pid`, `type`, `name`, `alias`, `rename`, `qp_img`, `qp_img2`, `img`, `qp_icon`, `qp_un_icon`, `list_mode`, `quit`, `sort`, `hot_sort`, `status`, `hot_status`, `update_at`, `switch`, `m_start_time`, `m_end_time`, `across_sort`, `across_status`) VALUES (137, 4, 'NG', 'NG', 'NG', 'NG电子', NULL, NULL, 'https://img.caacaya.com/lodi/menu/ng.png', NULL, NULL, '1', '1', NULL, 0, 'enabled', 'disabled', NULL, 'enabled', NULL, NULL, NULL, 'enabled');

ALTER TABLE `user_dml` ADD COLUMN `NG` int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `BTI`;

INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13820, 'caishens-cash', 137, 'God Of Fortune', 'God Of Fortune', 'Slot', 'GodOfFortune', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/God Of Fortune.png', NULL, 0, '2022-11-19 17:32:04', '2022-11-19 17:32:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13816, 'fulong', 137, 'Longevity Dragon', 'Longevity Dragon', 'Slot', 'LongevityDragon', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Longevity Dragon.png', NULL, 0, '2022-11-19 17:32:04', '2022-11-19 17:32:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13817, 'gates-kunlun', 137, 'Gates Of Kunlun', 'Gates Of Kunlun', 'Slot', 'GatesOfKunlun', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Gates Of Kunlun.png', NULL, 0, '2022-11-19 17:32:04', '2022-11-19 17:32:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13815, 'lucky-neko', 137, 'Sakura Neko', 'Sakura Neko', 'Slot', 'SakuraNeko', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Sakura Neko.png', NULL, 0, '2022-11-19 17:32:04', '2022-11-19 17:32:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13814, 'mahjong-fortune', 137, 'Mahjong Fortune', 'Mahjong Fortune', 'Slot', 'MahjongFortune', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Mahjong Fortune.png', NULL, 0, '2022-11-19 17:32:04', '2022-11-19 17:32:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13821, 'mermaid', 137, 'Mermaid\'s Treasure', 'Mermaid\'s Treasure', 'Slot', 'MermaidsTreasure', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Mermaids Treasure.png', NULL, 0, '2022-11-19 17:34:59', '2022-11-19 17:34:59', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13822, 'persian-gems', 137, 'Persian Gems', 'Persian Gems', 'Slot', 'PersianGems', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Persian Gems.png', NULL, 0, '2022-11-19 17:32:05', '2022-11-19 17:32:05', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13819, 'playboy-mansion', 137, 'Wild West Saloon', 'Wild West Saloon', 'Slot', 'WildWestSaloon', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Wild West Saloon.png', NULL, 0, '2022-11-19 17:32:05', '2022-11-19 17:32:05', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13818, 'queen-aztec', 137, 'Queen Of Aztec', 'Queen Of Aztec', 'Slot', 'QueenOfAztec', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Queen Of Aztec.png', NULL, 0, '2022-11-19 17:32:05', '2022-11-19 17:32:05', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13812, 'sanguo', 137, 'SanGuo - The Brotherhood', 'SanGuo - The Brotherhood', 'Slot', 'SanGuoTheBrotherhood', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/SanGuo The Brotherhood.png', NULL, 0, '2022-11-19 17:35:04', '2022-11-19 17:35:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13809, 'stallion-gold', 137, 'Stallion Princess', 'Stallion Princess', 'Slot', 'StallionPrincess', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Stallion Princess.png', NULL, 0, '2022-11-19 17:32:05', '2022-11-19 17:32:05', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (13813, 'sweet-bonanza', 137, 'Sugary Bonanza', 'Sugary Bonanza', 'Slot', 'SugaryBonanza', NULL, 'https://img.caacaya.com/lodi/game/vert/ng/Sugary Bonanza.png', NULL, 0, '2022-11-19 17:32:05', '2022-11-19 17:32:05', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);

DROP TABLE IF EXISTS `game_order_ng`;
CREATE TABLE `game_order_ng`  (
      `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
      `user_id` int(10) UNSIGNED NOT NULL COMMENT '用户id',
      `roundId` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏记录的唯一标识符',
      `amount` decimal(10, 2) NOT NULL COMMENT '玩家下注的金额',
      `earn` decimal(10, 2) NOT NULL COMMENT '玩家赚取的金钱数额',
      `betSize` decimal(10, 2) NOT NULL COMMENT '投注大小',
      `betStatus` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '投注状态（PENDING待定；RESOLVED解决；OPERATOR_UNKNOWN_ERROR）',
      `channel` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '玩家使用的平台，包括PC、Mobile',
      `playerBalance` decimal(10, 2) UNSIGNED NOT NULL COMMENT '用户余额',
      `playerNativeId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '玩家姓名',
      `gameName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏名称',
      `gameCode` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏code',
      `created` datetime(0) NOT NULL COMMENT '创建记录的日期和时间',
      `updated` datetime(0) NOT NULL COMMENT '上次更新记录的日期和时间',
      PRIMARY KEY (`id`) USING BTREE,
      UNIQUE INDEX `uniq_logId`(`roundId`) USING BTREE,
      INDEX `idx_created`(`created`) USING BTREE,
      INDEX `idx_pc`(`playerNativeId`, `created`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

ALTER TABLE `game_order_qt`
    MODIFY COLUMN `initiated` datetime(0) NOT NULL COMMENT '游戏局创建的日期和时间' AFTER `tableId`,
    MODIFY COLUMN `completed` datetime(0) NOT NULL COMMENT '游戏局完成的日期和时间' AFTER `initiated`;