INSERT INTO `game_menu`(`id`, `pid`, `type`, `name`, `alias`, `rename`, `qp_img`, `qp_img2`, `img`, `qp_icon`, `qp_un_icon`, `list_mode`, `quit`, `sort`, `hot_sort`, `status`, `hot_status`, `update_at`, `switch`, `m_start_time`, `m_end_time`, `across_sort`, `across_status`) VALUES (144, 23, 'TCG', 'TCG', 'TCG', 'TCG彩票', NULL, NULL, 'https://img.caacaya.com/lodi/menu/tcg.png', NULL, NULL, '1', '1', NULL, 0, 'enabled', 'disabled', NULL, 'enabled', NULL, NULL, NULL, 'enabled');

INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14268, '4DSGC@', 144, 'Singapore 4D', 'Singapore 4D', 'CP', 'Singapore4D', NULL, 'https://img.caacaya.com/game/tcg/4DSGC@.png', NULL, 1, 0, '2023-01-11 18:18:47', '2023-01-11 18:18:47', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14269, '4DTWC@', 144, 'Taiwan 4D', 'Taiwan 4D', 'CP', 'Taiwan4D', NULL, 'https://img.caacaya.com/game/tcg/4DTWC@.png', NULL, 2, 0, '2023-01-11 18:18:57', '2023-01-11 18:18:57', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14215, 'AGVNC', 144, 'An Giang', 'An Giang', 'CP', 'AnGiang', NULL, 'https://img.caacaya.com/game/tcg/AGVNC.png', NULL, 3, 0, '2023-01-11 18:08:03', '2023-01-11 18:08:03', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14259, 'BCLC', 144, 'Canada BCLC', 'Canada BCLC', 'CP', 'CanadaBCLC', NULL, 'https://img.caacaya.com/game/tcg/BCLC.png', NULL, 4, 0, '2023-01-11 18:13:54', '2023-01-11 18:13:54', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14216, 'BDHVNC', 144, 'Binh Dinh', 'Binh Dinh', 'CP', 'BinhDinh', NULL, 'https://img.caacaya.com/game/tcg/BDHVNC.png', NULL, 5, 0, '2023-01-11 18:08:07', '2023-01-11 18:08:07', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14217, 'BDVNC', 144, 'Binh Duong', 'Binh Duong', 'CP', 'BinhDuong', NULL, 'https://img.caacaya.com/game/tcg/BDVNC.png', NULL, 6, 0, '2023-01-11 18:08:09', '2023-01-11 18:08:09', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14218, 'BLVNC', 144, 'Bac Lieu', 'Bac Lieu', 'CP', 'BacLieu', NULL, 'https://img.caacaya.com/game/tcg/BLVNC.png', NULL, 7, 0, '2023-01-11 18:08:10', '2023-01-11 18:08:10', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14219, 'BNVNC', 144, 'Bac Ninh', 'Bac Ninh', 'CP', 'BacNinh', NULL, 'https://img.caacaya.com/game/tcg/BNVNC.png', NULL, 8, 0, '2023-01-11 18:08:11', '2023-01-11 18:08:11', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14220, 'BPVNC', 144, 'Binh Phuoc', 'Binh Phuoc', 'CP', 'BinhPhuoc', NULL, 'https://img.caacaya.com/game/tcg/BPVNC.png', NULL, 9, 0, '2023-01-11 18:08:14', '2023-01-11 18:08:14', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14221, 'BTHVNC', 144, 'Binh Thuan', 'Binh Thuan', 'CP', 'BinhThuan', NULL, 'https://img.caacaya.com/game/tcg/BTHVNC.png', NULL, 10, 0, '2023-01-11 18:08:17', '2023-01-11 18:08:17', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14233, 'CMVNC', 144, 'Ca Mau', 'Ca Mau', 'CP', 'CaMau', NULL, 'https://img.caacaya.com/game/tcg/CMVNC.png', NULL, 11, 0, '2023-01-11 18:08:19', '2023-01-11 18:08:19', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14222, 'CTVNC', 144, 'Can Tho', 'Can Tho', 'CP', 'CanTho', NULL, 'https://img.caacaya.com/game/tcg/CTVNC.png', NULL, 12, 0, '2023-01-11 18:08:20', '2023-01-11 18:08:20', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14223, 'DLKVNC', 144, 'Daklak', 'Daklak', 'CP', 'Daklak', NULL, 'https://img.caacaya.com/game/tcg/DLKVNC.png', NULL, 13, 0, '2023-01-11 18:08:22', '2023-01-11 18:08:22', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14265, 'DMCMAS@', 144, 'Lotere DMC', 'Lotere DMC', 'CP', 'LotereDMC', NULL, 'https://img.caacaya.com/game/tcg/DMCMAS@.png', NULL, 14, 0, '2023-01-11 18:19:28', '2023-01-11 18:19:28', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14224, 'DNGVNC', 144, 'Da Nang', 'Da Nang', 'CP', 'DaNang', NULL, 'https://img.caacaya.com/game/tcg/DNGVNC.png', NULL, 15, 0, '2023-01-11 18:08:26', '2023-01-11 18:08:26', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14225, 'DNOVNC', 144, 'Dac Nong', 'Dac Nong', 'CP', 'DacNong', NULL, 'https://img.caacaya.com/game/tcg/DNOVNC.png', NULL, 16, 0, '2023-01-11 18:08:28', '2023-01-11 18:08:28', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14226, 'DNVNC', 144, 'Dong Nai', 'Dong Nai', 'CP', 'DongNai', NULL, 'https://img.caacaya.com/game/tcg/DNVNC.png', NULL, 17, 0, '2023-01-11 18:08:30', '2023-01-11 18:08:30', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14234, 'DTVNC', 144, 'Dong Thap', 'Dong Thap', 'CP', 'DongThap', NULL, 'https://img.caacaya.com/game/tcg/DTVNC.png', NULL, 18, 0, '2023-01-11 18:08:32', '2023-01-11 18:08:32', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14261, 'FCKL8', 144, 'Beijing Keno', 'Beijing Keno', 'CP', 'BeijingKeno', NULL, 'https://img.caacaya.com/game/tcg/FCKL8.png', NULL, 19, 0, '2023-01-11 18:14:39', '2023-01-11 18:14:39', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14227, 'GLVNC', 144, 'Gia Lai', 'Gia Lai', 'CP', 'GiaLai', NULL, 'https://img.caacaya.com/game/tcg/GLVNC.png', NULL, 20, 0, '2023-01-11 18:08:36', '2023-01-11 18:08:36', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14263, 'GRKENO', 144, 'Greece Keno', 'Greece Keno', 'CP', 'GreeceKeno', NULL, 'https://img.caacaya.com/game/tcg/GRKENO.png', NULL, 21, 0, '2023-01-11 18:14:54', '2023-01-11 18:14:54', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14228, 'HCMVNC', 144, 'Ho Chi Minh', 'Ho Chi Minh', 'CP', 'HoChiMinh', NULL, 'https://img.caacaya.com/game/tcg/HCMVNC.png', NULL, 22, 0, '2023-01-11 18:08:40', '2023-01-11 18:08:40', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14229, 'HGVNC', 144, 'Hau Giang', 'Hau Giang', 'CP', 'HauGiang', NULL, 'https://img.caacaya.com/game/tcg/HGVNC.png', NULL, 23, 0, '2023-01-11 18:08:42', '2023-01-11 18:08:42', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14270, 'HKSTOCK', 144, 'Hang Seng Index', 'Hang Seng Index', 'CP', 'HangSengIndex', NULL, 'https://img.caacaya.com/game/tcg/HKSTOCK.png', NULL, 24, 0, '2023-01-11 18:08:44', '2023-01-11 18:08:44', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14252, 'HNVNC', 144, 'Hanoi North', 'Hanoi North', 'CP', 'HanoiNorth', NULL, 'https://img.caacaya.com/game/tcg/HNVNC.png', NULL, 25, 0, '2023-01-11 18:08:45', '2023-01-11 18:08:45', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14230, 'HPVNC', 144, 'Hai Phong', 'Hai Phong', 'CP', 'HaiPhong', NULL, 'https://img.caacaya.com/game/tcg/HPVNC.png', NULL, 26, 0, '2023-01-11 18:08:47', '2023-01-11 18:08:47', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14271, 'INSTOCK', 144, 'S&P BSE Sensex', 'S&P BSE Sensex', 'CP', 'S&PBSESensex', NULL, 'https://img.caacaya.com/game/tcg/INSTOCK.png', NULL, 27, 0, '2023-01-11 18:08:56', '2023-01-11 18:08:56', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14272, 'JPSTOCK', 144, 'Nikkei 225', 'Nikkei 225', 'CP', 'Nikkei225', NULL, 'https://img.caacaya.com/game/tcg/JPSTOCK.png', NULL, 28, 0, '2023-01-11 18:08:58', '2023-01-11 18:08:58', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14231, 'KHVNC', 144, 'Khanh Hoa', 'Khanh Hoa', 'CP', 'KhanhHoa', NULL, 'https://img.caacaya.com/game/tcg/KHVNC.png', NULL, 29, 0, '2023-01-11 18:09:00', '2023-01-11 18:09:00', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14273, 'KRSTOCK', 144, 'KTOP 30 Index', 'KTOP 30 Index', 'CP', 'KTOP30Index', NULL, 'https://img.caacaya.com/game/tcg/KRSTOCK.png', NULL, 30, 0, '2023-01-11 18:09:02', '2023-01-11 18:09:02', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14232, 'KTVNC', 144, 'Kontum', 'Kontum', 'CP', 'Kontum', NULL, 'https://img.caacaya.com/game/tcg/KTVNC.png', NULL, 31, 0, '2023-01-11 18:09:04', '2023-01-11 18:09:04', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14253, 'LAOCAI', 144, 'LAO Gov. lott', 'LAO Gov. lott', 'CP', 'LAOGov.lott', NULL, 'https://img.caacaya.com/game/tcg/LAOCAI.png', NULL, 32, 0, '2023-01-11 18:09:06', '2023-01-11 18:09:06', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14235, 'LDVNC', 144, 'Lam Dong', 'Lam Dong', 'CP', 'LamDong', NULL, 'https://img.caacaya.com/game/tcg/LDVNC.png', NULL, 33, 0, '2023-01-11 18:09:07', '2023-01-11 18:09:07', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14266, 'MN4DMAS@', 144, 'Magnum 4D', 'Magnum 4D', 'CP', 'Magnum4D', NULL, 'https://img.caacaya.com/game/tcg/MN4DMAS@.png', NULL, 34, 0, '2023-01-11 18:19:40', '2023-01-11 18:19:40', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14274, 'MYSTOCK', 144, 'FBMKLCI Index', 'FBMKLCI Index', 'CP', 'FBMKLCIIndex', NULL, 'https://img.caacaya.com/game/tcg/MYSTOCK.png', NULL, 35, 0, '2023-01-11 18:09:11', '2023-01-11 18:09:11', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14236, 'NDVNC', 144, 'Nam Dinh', 'Nam Dinh', 'CP', 'NamDinh', NULL, 'https://img.caacaya.com/game/tcg/NDVNC.png', NULL, 36, 0, '2023-01-11 18:09:12', '2023-01-11 18:09:12', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14237, 'NTVNC', 144, 'Ninh Thuan', 'Ninh Thuan', 'CP', 'NinhThuan', NULL, 'https://img.caacaya.com/game/tcg/NTVNC.png', NULL, 37, 0, '2023-01-11 18:09:14', '2023-01-11 18:09:14', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14264, 'NZLKENO', 144, 'New Zealand Keno', 'New Zealand Keno', 'CP', 'NewZealandKeno', NULL, 'https://img.caacaya.com/game/tcg/NZLKENO.png', NULL, 38, 0, '2023-01-11 18:15:21', '2023-01-11 18:15:21', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14238, 'PYVNC', 144, 'Phu Yen', 'Phu Yen', 'CP', 'PhuYen', NULL, 'https://img.caacaya.com/game/tcg/PYVNC.png', NULL, 39, 0, '2023-01-11 18:09:17', '2023-01-11 18:09:17', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14239, 'QBVNC', 144, 'Quang Binh', 'Quang Binh', 'CP', 'QuangBinh', NULL, 'https://img.caacaya.com/game/tcg/QBVNC.png', NULL, 40, 0, '2023-01-11 18:09:19', '2023-01-11 18:09:19', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14240, 'QNHVNC', 144, 'Quang Ninh', 'Quang Ninh', 'CP', 'QuangNinh', NULL, 'https://img.caacaya.com/game/tcg/QNHVNC.png', NULL, 41, 0, '2023-01-11 18:09:20', '2023-01-11 18:09:20', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14241, 'QNIVNC', 144, 'Quang Ngai', 'Quang Ngai', 'CP', 'QuangNgai', NULL, 'https://img.caacaya.com/game/tcg/QNIVNC.png', NULL, 42, 0, '2023-01-11 18:09:21', '2023-01-11 18:09:21', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14242, 'QNMVNC', 144, 'Quang Nam', 'Quang Nam', 'CP', 'QuangNam', NULL, 'https://img.caacaya.com/game/tcg/QNMVNC.png', NULL, 43, 0, '2023-01-11 18:09:23', '2023-01-11 18:09:23', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14243, 'QTVNC', 144, 'Quang Tri', 'Quang Tri', 'CP', 'QuangTri', NULL, 'https://img.caacaya.com/game/tcg/QTVNC.png', NULL, 44, 0, '2023-01-11 18:09:25', '2023-01-11 18:09:25', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14275, 'SGSTOCK', 144, 'Straits Times Index', 'Straits Times Index', 'CP', 'StraitsTimesIndex', NULL, 'https://img.caacaya.com/game/tcg/SGSTOCK.png', NULL, 45, 0, '2023-01-11 18:09:27', '2023-01-11 18:09:27', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14276, 'SHSTOCK', 144, 'SSE Composite', 'SSE Composite', 'CP', 'SSEComposite', NULL, 'https://img.caacaya.com/game/tcg/SHSTOCK.png', NULL, 46, 0, '2023-01-11 18:09:28', '2023-01-11 18:09:28', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14262, 'SKKENO', 144, 'Slovakia Keno', 'Slovakia Keno', 'CP', 'SlovakiaKeno', NULL, 'https://img.caacaya.com/game/tcg/SKKENO.png', NULL, 47, 0, '2023-01-11 18:15:43', '2023-01-11 18:15:43', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14244, 'STVNC', 144, 'Soc Trang', 'Soc Trang', 'CP', 'SocTrang', NULL, 'https://img.caacaya.com/game/tcg/STVNC.png', NULL, 48, 0, '2023-01-11 18:09:34', '2023-01-11 18:09:34', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14277, 'SZSTOCK', 144, 'SZSE Component', 'SZSE Component', 'CP', 'SZSEComponent', NULL, 'https://img.caacaya.com/game/tcg/SZSTOCK.png', NULL, 49, 0, '2023-01-11 18:09:36', '2023-01-11 18:09:36', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14245, 'TBHVNC', 144, 'Thai Binh', 'Thai Binh', 'CP', 'ThaiBinh', NULL, 'https://img.caacaya.com/game/tcg/TBHVNC.png', NULL, 50, 0, '2023-01-11 18:09:38', '2023-01-11 18:09:38', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14258, 'TCGKENO', 144, 'Turbo Keno', 'Turbo Keno', 'CP', 'TurboKeno', NULL, 'https://img.caacaya.com/game/tcg/TCGKENO.png', NULL, 51, 0, '2023-01-11 18:15:55', '2023-01-11 18:15:55', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14175, 'TCGSEA3D1', 144, 'TCG60s3D', 'TCG60s3D', 'CP', 'TCG60s3D', NULL, 'https://img.caacaya.com/game/tcg/TCGSEA3D1.png', NULL, 52, 0, '2023-01-11 18:09:42', '2023-01-11 18:09:42', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14176, 'TCGSEA3D3', 144, 'TCG180s3D', 'TCG180s3D', 'CP', 'TCG180s3D', NULL, 'https://img.caacaya.com/game/tcg/TCGSEA3D3.png', NULL, 53, 0, '2023-01-11 18:09:44', '2023-01-11 18:09:44', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14177, 'TCGSEA3D5', 144, 'TCG300s3D', 'TCG300s3D', 'CP', 'TCG300s3D', NULL, 'https://img.caacaya.com/game/tcg/TCGSEA3D5.png', NULL, 54, 0, '2023-01-11 18:09:46', '2023-01-11 18:09:46', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14254, 'TCGSEA4D1', 144, 'TCG60s4D', 'TCG60s4D', 'CP', 'TCG60s4D', NULL, 'https://img.caacaya.com/game/tcg/TCGSEA4D1.png', NULL, 55, 0, '2023-01-11 18:09:48', '2023-01-11 18:09:48', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14255, 'TCGSEA4D3', 144, 'TCG180s4D', 'TCG180s4D', 'CP', 'TCG180s4D', NULL, 'https://img.caacaya.com/game/tcg/TCGSEA4D3.png', NULL, 56, 0, '2023-01-11 18:09:49', '2023-01-11 18:09:49', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14256, 'TCGSEA4D5', 144, 'TCG300s4D', 'TCG300s4D', 'CP', 'TCG300s4D', NULL, 'https://img.caacaya.com/game/tcg/TCGSEA4D5.png', NULL, 57, 0, '2023-01-11 18:09:51', '2023-01-11 18:09:51', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14173, 'TCGTURBO3D', 144, 'TCGTurbo3D', 'TCGTurbo3D', 'CP', 'TCGTurbo3D', NULL, 'https://img.caacaya.com/game/tcg/TCGTURBO3D.png', NULL, 58, 0, '2023-01-11 18:09:53', '2023-01-11 18:09:53', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14246, 'TGVNC', 144, 'Tien Giang', 'Tien Giang', 'CP', 'TienGiang', NULL, 'https://img.caacaya.com/game/tcg/TGVNC.png', NULL, 59, 0, '2023-01-11 18:09:55', '2023-01-11 18:09:55', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14174, 'THAIGOV', 144, 'THAI Gov. lott', 'THAI Gov. lott', 'CP', 'THAIGovlott', NULL, 'https://img.caacaya.com/game/tcg/THAIGOV.png', NULL, 60, 0, '2023-01-11 18:09:56', '2023-01-11 18:09:56', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14278, 'THSTOCK', 144, 'SET Index', 'SET Index', 'CP', 'SETIndex', NULL, 'https://img.caacaya.com/game/tcg/THSTOCK.png', NULL, 61, 0, '2023-01-11 18:09:58', '2023-01-11 18:09:58', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14247, 'TNVNC', 144, 'Tay Ninh', 'Tay Ninh', 'CP', 'TayNinh', NULL, 'https://img.caacaya.com/game/tcg/TNVNC.png', NULL, 62, 0, '2023-01-11 18:10:01', '2023-01-11 18:10:01', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14267, 'TOTOMAS@', 144, 'TOTO 4D', 'TOTO 4D', 'CP', 'TOTO4D', NULL, 'https://img.caacaya.com/game/tcg/TOTOMAS@.png', NULL, 63, 0, '2023-01-11 18:19:52', '2023-01-11 18:19:52', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14248, 'TTHVNC', 144, 'Thua Thien Hue', 'Thua Thien Hue', 'CP', 'ThuaThienHue', NULL, 'https://img.caacaya.com/game/tcg/TTHVNC.png', NULL, 64, 0, '2023-01-11 18:10:08', '2023-01-11 18:10:08', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14249, 'TVVNC', 144, 'Tra Vinh', 'Tra Vinh', 'CP', 'TraVinh', NULL, 'https://img.caacaya.com/game/tcg/TVVNC.png', NULL, 65, 0, '2023-01-11 18:10:11', '2023-01-11 18:10:11', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14257, 'TWBINGO', 144, 'Taiwan Bingo', 'Taiwan Bingo', 'CP', 'TaiwanBingo', NULL, 'https://img.caacaya.com/game/tcg/TWBINGO.png', NULL, 66, 0, '2023-01-11 18:16:20', '2023-01-11 18:16:20', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14279, 'TWSTOCK', 144, 'Taiwan 50 Index', 'Taiwan 50 Index', 'CP', 'Taiwan50Index', NULL, 'https://img.caacaya.com/game/tcg/TWSTOCK.png', NULL, 67, 0, '2023-01-11 18:10:13', '2023-01-11 18:10:13', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14250, 'VLVNC', 144, 'Vinh Long', 'Vinh Long', 'CP', 'VinhLong', NULL, 'https://img.caacaya.com/game/tcg/VLVNC.png', NULL, 68, 0, '2023-01-11 18:10:15', '2023-01-11 18:10:15', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14251, 'VTVNC', 144, 'Vung Tau', 'Vung Tau', 'CP', 'VungTau', NULL, 'https://img.caacaya.com/game/tcg/VTVNC.png', NULL, 69, 0, '2023-01-11 18:10:18', '2023-01-11 18:10:18', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);
INSERT INTO `game_3th`(`id`, `kind_id`, `game_id`, `game_name`, `rename`, `type`, `alias`, `qp_img`, `game_img`, `mark_img`, `sort`, `hot_sort`, `created`, `updated`, `maintain`, `is_hot`, `status`, `hot_status`, `across_sort`, `across_status`, `extension_img`, `is_freespin`) VALUES (14260, 'WCLC', 144, 'Canada WCLC', 'Canada WCLC', 'CP', 'CanadaWCLC', NULL, 'https://img.caacaya.com/game/tcg/WCLC.png', NULL, 70, 0, '2023-01-11 18:16:31', '2023-01-11 18:16:31', 'tobemaintain', 0, 'enabled', 'disabled', NULL, 'enabled', NULL, 0);

ALTER TABLE `user_dml` ADD COLUMN `TCG` int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `EVORT`;

DROP TABLE IF EXISTS `game_order_tcg`;
CREATE TABLE `game_order_tcg`  (
       `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
       `user_id` int(30) NULL DEFAULT NULL COMMENT '用户id',
       `betAmount` decimal(10, 2) UNSIGNED NOT NULL COMMENT '投注金额',
       `actualBetAmount` decimal(10, 2) UNSIGNED NOT NULL COMMENT '实际投注金额',
       `orderNum` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '投注订单号',
       `gameCode` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏代码',
       `device` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '使用设备：网页：WEB; 手机：MTH',
       `betNum` int(10) UNSIGNED NOT NULL COMMENT '注数',
       `winAmount` decimal(10, 2) NOT NULL COMMENT '中奖金额',
       `netPNL` decimal(10, 2) NOT NULL COMMENT '净输赢',
       `betStatus` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单状态(1:已中奖｜2:未中奖 ｜3:取消 | 4:和)',
       `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '玩家帐号',
       `numero` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '期号',
       `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '彩种',
       `bettingContent` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '投注实际内容',
       `playBonus` decimal(10, 2) UNSIGNED NOT NULL COMMENT '赔率',
       `winningNumber` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '开奖号码',
       `playName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '玩法名称',
       `gameGroupName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '彩种组',
       `multiple` int(10) NOT NULL COMMENT '下注倍数',
       `playId` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '玩法ID',
       `betTime` datetime(0) NOT NULL COMMENT '投注时间',
       `settlementTime` datetime(0) NOT NULL COMMENT '结算时间',
       PRIMARY KEY (`id`) USING BTREE,
       UNIQUE INDEX `uniq_orderNo`(`orderNum`) USING BTREE,
       INDEX `idx_created`(`betTime`) USING BTREE,
       INDEX `idx_pc`(`username`, `betTime`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;