CREATE TABLE `rpt_channel_total`  (
`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`channel_id` varchar(255) NULL DEFAULT NULL COMMENT '渠道id',
`channel_name` varchar(255) NULL DEFAULT NULL COMMENT '渠道名称',
`award_money` decimal(18, 2) NULL DEFAULT NULL COMMENT '月俸',
`click` int(11) NULL DEFAULT NULL COMMENT '新增访问次数',
`cz_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '充值金额',
`cz_person` int(11) NULL DEFAULT NULL COMMENT '充值人数',
`qk_person` int(11) NULL DEFAULT NULL COMMENT '取款人数',
`qk_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '取款金额',
`tz_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '投注金额',
`pc_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '派彩金额',
`hd_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '活动彩金',
`hs_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '回水彩金',
`js_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '晋升彩金',
`zk_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '转卡彩金',
`fyz_amount` decimal(18, 2) NULL DEFAULT NULL COMMENT '返佣总金额',
`first_recharge_user` int(11) NULL DEFAULT NULL COMMENT '(新充人数)首次充值人数',
`first_recharge` decimal(18, 2) NULL DEFAULT NULL COMMENT '(新充充值金额)首次充值金额',
`first_withdraw` decimal(18, 2) NULL DEFAULT NULL COMMENT '首次取款金额',
`first_bet` decimal(18, 2) NULL DEFAULT NULL COMMENT '首次投注金额',
`first_prize` decimal(18, 2) NULL DEFAULT NULL COMMENT '首次派彩金额',
PRIMARY KEY (`id`) USING BTREE,
UNIQUE INDEX `uniq_channel_id`(`channel_id`) USING BTREE,
INDEX `idx_chan_name`(`channel_name`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1;